### ISSUE TITLE
Error (dotnet 3.1.300; MinVer 2.2): The specified version string does not conform to the recommended format - major.minor.build.revision

### ISSUE THREAD

**Issue by ghorsey** [adamralph/minver#342] opened 2020-05-21 05:02 UTC
## Version(s)

MinVer: `v2.2`
dotnet: `v3.1.300`
```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.202 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

## To reproduce

1. Add MinVer v2.2 to netstandard2.1 project
2. Set version values in csproj:
```
<Version>$(MinVerVersion)</Version>
<PackageVersion>$(MinVerVersion)</PackageVersion>
<FileVersion>$(MinVerMajor).$(MinVerMinor).$(MinVerPatch).0</FileVersion>
<AssemblyVersion>$(MinVerMajor).0.0.0</AssemblyVersion>
<MinVerTagPrefix>v</MinVerTagPrefix>
```
3. Run `dotnet restore`
4. Run `dotnet build`

## Expected behavior

Expect project to successfully build

## Actual behavior
```
obj\Debug\netstandard2.1\TS.Media.Domain.AssemblyInfo.cs(15,59): error CS7035: The specified version string does not conform to the recommended format - major.minor.build.revision [C:\code\truckspottr\microservices\Media\src\app\TS.Media.Domain\TS.Media.Domain.csproj]
obj\Debug\netstandard2.1\TS.Media.Domain.AssemblyInfo.cs(19,55): error CS7034: The specified version string does not conform to the required format - major[.minor[.build[.revision]]] [C:\code\truckspottr\microservices\Media\src\app\TS.Media.Domain\TS.Media.Domain.csproj]
```

**Comment by adamralph** [comment] 2020-05-21 06:20
@ghorsey thanks for raising this.

You should remove all of this:

```xml
<Version>$(MinVerVersion)</Version>
<PackageVersion>$(MinVerVersion)</PackageVersion>
<FileVersion>$(MinVerMajor).$(MinVerMinor).$(MinVerPatch).0</FileVersion>
<AssemblyVersion>$(MinVerMajor).0.0.0</AssemblyVersion>
```

MinVer does all this for you. The way you have it now, these properties will be set during initial evaluation of the project file, before the MinVer target has run, so all the MinVer variables will be empty strings. If, for any reason, you want to customise any of the property values, you must do that after the MinVer target has run, as [described in the FAQ](https://github.com/adamralph/minver#can-i-use-the-version-calculated-by-minver-for-other-purposes).

**Comment by bording** [comment] 2020-05-25 17:48
This may actually be related to the fix needed for for the 3.1.300 SDK: #344

**Comment by adamralph** [comment] 2020-05-25 17:51
Actually, yes. Even if those properties are being set, MinVer should still then set them correctly when it runs.

**Comment by ghorsey** [comment] 2020-05-25 17:52
@bording It may be.  I could swear this code would compile before updating dotnet sdk to 3.1.300

**Comment by adamralph** [comment] 2020-05-25 17:53
@ghorsey yes, now that I look at it again, the fact that you are setting those properties in the csproj is not the problem.

BTW - you should still remove those lines.

**Comment by ghorsey** [comment] 2020-05-25 17:54
Yeah, giving that a go now on this current version to see if that workaround fixes my issue.

**Comment by adamralph** [comment] 2020-05-25 18:03
@ghorsey to be clear, removing those lines won't fix your issue. We need to release a new version of MinVer which changes the point at which the MinVer target is run.

**Comment by ghorsey** [comment] 2020-05-25 18:06
I am in early development (pre-production) so I can live with it.  Removing those lines did allow my build to succeed, which clears my blocker!  Thank you for the help!

**Comment by adamralph** [comment] 2020-05-25 18:09
Ah yes, I guess it allows your build to succeed because you are no longer setting an empty string as the version.

MinVer however, will still not work until we release the new version.

**Comment by adamralph** [comment] 2020-05-26 19:23
@ghorsey thanks again for raising this. Since this was caused by a breaking change in SDK 3.1.300, I'm not treating this as a bug in MinVer, so I'm withdrawing this issue in favour of https://github.com/adamralph/minver/pull/347.

**Closed by adamralph** 2020-05-26 19:23 UTC
Labels: duplicate
