### ISSUE TITLE
Failed to emit module Changing the version of an assembly reference is not allowed during debugging:  to "1.0.0.0"

### ISSUE THREAD

**Issue by Trapulo** [adamralph/minver#659] opened 2022-01-12 14:15 UTC
Hi,
I a VS2022 / .NET 6.0 solution where every project is using minver 2.5.0 I found that edit and continue does not work, and it's reporting this error after a code change:

Error	BC36970	Failed to emit module XXXX Changing the version of an assembly reference is not allowed during debugging:  XXXX changed version to "1.0.0.0"

Is this some problem caused by minver?

thanks

**Comment by adamralph** [comment] 2022-01-12 18:04
hi @Trapulo, I guess edit and continue could be triggering some form of rebuild which causes the MinVer target to run.

There is a [condition on the target](https://github.com/adamralph/minver/blob/fcffc4f59d2e8e2ae82cd9e9455480292ad10c45/MinVer/build/MinVer.targets#L14) for `'$(DesignTimeBuild)' != 'true'`, but this isn't enough.

I'll take a closer look if and when I get time, but in the meantime perhaps you could experiment by tweaking the conditions on the target with reference to some variable which indicates that an edit and continue is happening.

**Comment by adamralph** [comment] 2022-01-29 11:52
I'm finding it difficult to understand the problem. As per the [issue template](https://github.com/adamralph/minver/issues/new?assignees=&labels=bug&template=bug_report.md&title=) can you please post instructions for how to reproduce the problem?

**Comment by adamralph** [comment] 2022-02-24 07:51
@Trapulo since you haven't replied, I'm closing this now.

If you still believe there is a bug, please open a new issue using the [_Bug report_ template](https://github.com/adamralph/minver/issues/new?assignees=&labels=bug&template=bug_report.md&title=).

**Closed by adamralph** 2022-02-24 07:51 UTC
Labels: bug, invalid
