### ISSUE TITLE
Suddenly getting an old version number

### ISSUE THREAD

**Issue by alexeyzimarev** [adamralph/minver#238] opened 2019-06-17 19:28 UTC
I wrote my experience in Twitter before, on a larger project, but now I have a fresh repo, a couple of days old. The only tag I have there is 0.9.0 and the last version was 0.9.0-alpha.0.20. But after the last merge, minver gives me 0.9.0-alpha.0.18.

What can I do to diagnose this?

**Comment by bording** [comment] 2019-06-17 20:04
Is the repo something you can share? Being able to see an actual way to reproduce the behavior is going to be very helpful here.

**Comment by alexeyzimarev** [comment] 2019-06-17 21:13
I tagged the repo and after the new tag, it goes fine. When it happens again, I can put it to a private repo and send an invite.

**Comment by adamralph** [comment] 2019-06-18 04:27
I suspect this happened:

```
*   18
|\  merge
|*  20
|*  19
|*  18
|/  branch
*   17
```

If so, that is by design and expected.

**Comment by alexeyzimarev** [comment] 2019-06-18 05:56
No, there were no branches, just master

**Comment by adamralph** [comment] 2019-06-18 11:51
OK, in that case, we'll definitely need a repro.

It may also help to set

```xml
<MinVerVerbosity>diagnostic</MinVerVerbosity>
```

which will tell you exactly how MinVer walks the commit history.

**Comment by adamralph** [comment] 2019-07-28 10:28
@alexeyzimarev I'll close this issue for now. The next time you observe this behaviour and you are able to provide us with a repro, please either re-open the issue or open a new one. Thanks!

**Closed by adamralph** 2019-07-28 10:28 UTC
Labels: question
