### ISSUE TITLE
Expose variables to CI systems

### ISSUE THREAD

**Issue by bording** [adamralph/minver#224] opened 2019-04-22 16:53 UTC
Per the the [twitter conversation](https://twitter.com/bording/status/1120347182828281856), MinVer calculated values are not accessible in later stages of a CI pipeline, and the version number is not surfaced up to the CI UI.

Other tools like GitVersion and Nerdbank.GitVersioning have custom code to handle integrating with various CI systems.

It seems like it would be worth investigating adding some similar form of CI integration to MinVer as well.

CC: @mauroservienti

**Comment by mauroservienti** [comment] 2019-04-26 05:02
The reason for this one is mainly if further steps, after building and packaging, should be performed during the build and these further steps require the build number generated by MinVer. One use case is: if the build process automatically pushes to nuget it’s nice to also automatically generate a release in GH pushing there the nuget package and build artifacts. In theory, if I understood correctly how things work, this could also be done by a separate package that integrated in the same way with MS Build as a target. Not sure if it’s possible to plugin into the MinVer CLI though.

**Comment by adamralph** [comment] 2019-04-26 05:48
@mauroservienti one thing to bear in mind is that you don't actually want the MinVer version for this purpose. What you really want is the _tag_. For example, a MinVer version could have build metadata appended to it, and while things like the NuGet gallery are SemVer-aware, GitHub releases aren't, so you don't want a release like `1.0.0+build.123`, which doesn't match your `1.0.0` tag. Tags are already surfaced in most CI systems, e.g. in `APPVEYOR_REPO_TAG_NAME` in Appveyor.

That said, this doesn't always work as desired. E.g. in Appveyor there is a bug which means that tags added to commits which are not at the tip of a branch do not always trigger builds. For that reason, in order to build an RTM from the same tag as the last RC, I've sometimes had to manually trigger a rebuild of the RC tag after adding an RTM tag to the same commit. In that case, `APPVEYOR_REPO_TAG_NAME` will still contain the RC tag instead of the RTM tag which MinVer used for versioning. For that reason, we'd still need MinVer to surface the _tag_ (not the version) to the build environment somehow.

**Comment by bording** [comment] 2019-04-26 13:55
If MinVer was exposing all of the values it was calculating, then that would work as well since you'd be able to construct whatever you needed from them.

**Comment by adamralph** [comment] 2019-04-28 13:24
@mauroservienti what are you building? Is it just NuGet packages?

**Comment by mauroservienti** [comment] 2019-04-28 13:37
In my case it’s just nuget packages, yes.

**Comment by adamralph** [comment] 2019-04-28 13:43
OK, just to check, what is the value of releasing NuGet packages to GitHub?

**Comment by mauroservienti** [comment] 2019-04-28 20:27
Nowadays none. There was value when it wasn’t easy to download packages from Nuget without VS or any nuget client. My original question came from my previous experience/workflow with GitVersion. GitVersion can use tags but doesn’t need tags so I was used to allow GitVersion to generate the build version for me given that I was using GitFlow. In such a scenario was very handy to allow the build server to:

- push to nuget/MyGet automatically 
- create a GH release and tag when merging a release branch to master

Now that I’m more acquainted with MinVer I understood that non è of the above make sense with MinVer, and this is fine.

That being said, I guess that out there there are plenty of tools that are run during builds but not as part of msbuild, they probably greatly benefit of such a feature. I don’t need it anymore, though.

**Comment by adamralph** [comment] 2019-05-01 18:52
Thanks @mauroservienti. That all makes sense.

@bording do you have a currently have a need for this feature?

**Comment by bording** [comment] 2019-05-01 19:00
Looking at the current Particular CI system, yes we would need this for a couple things:

- The calculated version number is used as the build number.
- We use the version number to determine if we should try to run .NET Core tests on a build, or just make that step pass automatically.

**Comment by shaynevanasperen** [comment] 2019-08-02 17:58
I would like to use this to create a zip file of my publish folder output of an ASP.NET Core web application, such that the zip file name includes the `MinVer` calculated variables. I want this so that I can push this artifact to our company's internal artifacts repository for later consumption by our continuous deployment pipeline.

**Comment by adamralph** [comment] 2019-08-03 10:45
@shaynevanasperen you could do that today by running the minver-cli tool, as [described in the docs](https://github.com/adamralph/minver/tree/2f7678cd55d6f3d29435b454aafba974fdb298e0#can-i-use-minver-to-version-software-which-is-not-built-using-a-net-sdk-style-project).

It's probably easier to run minver-cli and create your zip file as part of your build script, rather than through CI server configuration, but I'd argue that's better practice anyway, since it allows full reproduction of your build anywhere. Pushing the zip file to your artifacts repository could still be done via CI server config if required.

**Comment by adamralph** [comment] 2019-08-13 17:03
Discussed this with @bording earlier today. We agreed to close this issue for now, on the assumption that all of the use cases described so far can be satisfied today by running the `minver-cli` tool, as [described in the docs](https://github.com/adamralph/minver/tree/2f7678cd55d6f3d29435b454aafba974fdb298e0#can-i-use-minver-to-version-software-which-is-not-built-using-a-net-sdk-style-project), at the appropriate time during the build.

For example, there could be a build target(/step/task/etc.) which runs the minver-cli tool and captures the outputted version in an appropriate way for later use, which could be setting in a environment variable, writing something to the console for a CI system to detect, or even just setting a variable. Later targets(/steps/tasks/etc.) could use this value as required, to do things like:

- set the build number
- decide whether to run specific test suites or other things
- produce artifacts, such as zip files, named using the version

If/when arguments can be made for building more of this into MinVer itself, we will evaluate them.

The Particular CI system is not yet using MinVer, but if/when that is explored, we can investigate any proposals that come out of it.

@shaynevanasperen if you have any comments on my [suggestion above](https://github.com/adamralph/minver/issues/224#issuecomment-517915263), please feel free to chime in here or in a new issue.

Marking as `wontfix` for now, but that doesn't mean this issue cannot be re-opened and re-considered.

**Closed by adamralph** 2019-08-13 17:03 UTC
Labels: enhancement, wontfix

**Comment by shaynevanasperen** [comment] 2019-08-14 13:48
@adamralph Thanks. I agree with your assessment and course of action here. I managed to do what I needed to do using a bit of `PowerShell` script to extract the metadata from the output `dll`, but as you mentioned, there are other ways to do this too.
