### ISSUE TITLE
Error when git not installed

### ISSUE THREAD

**Issue by marinusmaurice** [adamralph/minver#776] opened 2022-06-17 04:18 UTC
## Version(s)
3.0
The version(s) in which you have observed the bug.

## To reproduce
Don't install git 
Steps to reproduce the behaviour:
1) On clean machine, 
2) install vs2022 with options for winforms/desktop dev in c# only
3) check out https://github.com/scriban/scriban try and build
 

## Expected behaviour
Rather return a message instead of throwing an exception

## Actual behaviour
returned in vs2022

1>Unhandled exception. System.InvalidOperationException: "git" is not present in PATH.
1> ---> System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
1>   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
1>   at System.Diagnostics.Process.Start()
1>Unhandled exception. System.InvalidOperationException: "git" is not present in PATH.
1>   at MinVer.Lib.GitCommand.TryRun(String args, String workingDirectory, ILogger log, String& output) in /_/MinVer.Lib/GitCommand.cs:line 32
1>   --- End of inner exception stack trace ---

A clear and concise description of what did happen.

## Workarounds

A clear and concise description of any workarounds you have identified.

**Comment by adamralph** [comment] 2022-06-18 09:15
@marinusmaurice the exception already contains a message:

> "git" is not present in PATH

Is the message not clear enough?

**Comment by mphelt** [comment] 2022-07-08 16:20
Hi @adamralph,

I have similar issue - I have a Windows Server 2019/2022 VMs with Github self-hosted runner, and even though I've installed the latest 'Git for Windows', and git was added to PATH, and Github runner seems to use git from PATH, MinVer doesn't see it.
Probably it's related to user's specific PATH, but that's not the point I would like to make.

I'm using MinVer together with [GitInfo](https://github.com/devlooped/GitInfo) to append branch name, etc. to informational version.
GitInfo seems to work even when git is not in PATH - what they do can be seen [here](https://github.com/devlooped/GitInfo/blob/9d943258ab8d2c578d97260b8f82eb14118c675e/src/GitInfo/build/GitInfo.targets#L1060).
They search for git in known directories.

I wonder if MinVer could do something similar in [GitCommand](https://github.com/adamralph/minver/blob/main/MinVer.Lib/GitCommand.cs), or at least search in 'C:\Program Files\Git\' when on Windows.
Or maybe you have something against such approach.

Please let me know your thoughts.
Thank you

**Comment by adamralph** [comment] 2022-07-08 17:34
@mphelt I'd rather not get into location probing if I can avoid it. Having Git present in PATH seems like a reasonable prerequisite. For example, could you modify your build script/workflow file to explicitly add the location of Git to PATH?

**Comment by adamralph** [comment] 2022-07-09 13:05
@marinusmaurice I guess I see what you mean:

![image](https://user-images.githubusercontent.com/677704/178106160-cdf64c57-1e4f-483e-9fbd-8a2750de0f19.png)

In the context of that Window, all you get is this error about a command failing, and it's only when you dig into the build log that you can find out that the underlying reason is that "git" is not present in PATH.

Thanks for raising this issue. This isn't a bug, since MinVer is working exactly as designed. I.e. there was never any intention to produce an MSBuild error telling the user that "git" is not present in PATH. For that reason, I am closing this bug as _invalid_. However, producing an MSBuild error for this known problem seems like an obvious enhancement, so I've raised https://github.com/adamralph/minver/issues/779 to capture it.

**Comment by adamralph** [comment] 2022-07-09 13:06
@mphelt if you'd like to continue the thread about location probing, please create a [feature request](https://github.com/adamralph/minver/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=).

**Closed by adamralph** 2022-07-09 13:05 UTC
Labels: bug
